#!/bin/bash

source /etc/backup.conf

if test -f $CMD_DUPLICITY;
then

	echo ""

	OIFS=$IFS

	while getopts ':p:' OPTION ; do
	  case "$OPTION" in
	    p)  EXCLUDE_GREP="| grep '$OPTARG'";;
	    *)   
			EXCLUDE_GREP="| grep -v 'Snapshot'"
			for i in ${EXCLUDE_LVS[@]}; do
		        EXCLUDE_GREP="$EXCLUDE_GREP | grep -v '$i'"
			done
			;;
	  esac
	done
	
	lvscantext=`eval /sbin/lvscan $EXCLUDE_GREP`
    datum=`cat /srv/storage/backup/lastbackup.txt`
	datumzeit="$(date +%Y-%m-%d-%H-%M-%S)"
	PROBLEM="false"
	IFS=$'\n'

	i=0

	export FTP_PASSWORD=$FTP_PASSWORD

	echo "-------------------------------------------------"
	echo "-------------------------------------------------"
	echo "----- BACKUP-JOB $datumzeit ------------"
	echo "-------------------------------------------------"
	for zeile in $lvscantext
	do
	        i=$[$i+1]
	        echo $zeile
	        ACTIVE=`echo $zeile | awk -v FS=" " '{print $1}'`
	        LV=`echo $zeile | awk -v FS="'" '{print $2}'`
	        LVname=`echo $LV | sed "s:/:_:g" | sed "s:_::"`
	        LVname=`echo $LV | awk -v FS="/" '{print $NF}'`
	        VGname=`echo $LV | sed "s:/${LVname}::"`

	        if [ $ACTIVE == "ACTIVE" ];
	        then
	                echo "Purge $LVname:"
	                echo "-------------------------------------------------"

	                echo "=> ${SAVETIME} alte Images vom FTP-Server entfernen"
	                $CMD_DUPLICITY remove-older-than 0 --force ftp://${FTP_USER}@${FTP_SERVER}/vm-images/${LVname}

                echo "-------------------------------------------------"
	        fi
	done
	
	unset FTP_PASSWORD

	IFS=$OIFS
else
	echo "duplicity was not found. please correct path-"
	echo "duplicity was not found. please correct path-" | mail -s "duplicity not found @ `hostname`!" $KONTAKTADRESSE
fi